name: flutter_tour_guide_example
description: Example app for flutter_tour_guide.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tour_guide:
    path: ../

flutter:
  uses-material-design: true
